In [10]:
import pandas as pd
from PyPDF2 import PdfReader

In [9]:
route_file = pd.read_xml('7a.rou.xml')
route_file

,id,begin,departLane,departSpeed,arrivalLane,from,to,end,number
0,ParkerRight,0.0,random,avg,current,8644213#8,102519704#0,3600.0,90
1,ParkerThru,0.0,random,avg,current,8644213#8,426843743,3600.0,417
2,ParkerLeft,0.0,random,avg,current,8644213#8,798289594#3,3600.0,3
3,HuntFromWRight,0.0,random,avg,current,426493699#0,-8644213#9,3600.0,5
4,HuntFromWThru,0.0,random,avg,current,426493699#0,102519704#0,3600.0,472
5,HuntFromWLeft,0.0,random,avg,current,426493699#0,426843743,3600.0,7
6,ForsythRight,0.0,random,avg,current,426843745#0,798289594#3,3600.0,139
7,ForsythThru,0.0,random,avg,current,426843745#0,-8644213#9,3600.0,215
8,ForsythLeft,0.0,random,avg,current,426843745#0,102519704#0,3600.0,19
9,HuntFromERight,0.0,random,avg,current,798289594#0,426843743,3600.0,12
10,HuntFromEThru,0.0,random,avg,current,798289594#0,798289594#3,3600.0,438
11,HuntFromELeft,0.0,random,avg,current,798289594#0,-8644213#9,3600.0,125

In [60]:
reader = PdfReader("Parker, Forsyth, Huntington.pdf")
demand = reader.pages[0]
demand_text = demand.extract_text()
demand_text = demand_text.replace('U ‐Turn', 'U-Turn')
demand_text = demand_text.replace('\n', ' ')
demand_text

'\xa0 Right Thru Left U-Turn Total Right Thru Left U-Turn Total Right Thru Left U-Turn Total Right Thru Left U-Turn Total 47 63 4 0 114 0 121 16 0 137 20 112 0 0 132 1 94 0 0 95 478 49 45 5 0 99 8 108 27 0 143 16 109 1 0 126 1 102 1 0 104 47218 55 9 0 82 1 105 34 0 140 24 99 1 0 124 1 134 4 0 139 48525 52 1 0 78 3 104 48 1 156 30 97 1 0 128 2 142 2 0 146 508 139 215 19 0 373 12 438 125 1 576 90 417 3 0 510 5 472 7 0 484 1943 53 61 4 0 118 5 83 23 0 111 27 114 0 0 141 3 132 1 0 136 50643 49 4 0 96 5 90 24 0 119 20 116 0 0 136 1 112 0 0 113 46436 50 2 0 88 5 90 36 0 131 10 107 0 0 117 1 135 0 0 136 47239 38 0 0 77 4 122 29 5 160 26 83 0 0 109 4 134 0 0 138 484 171 198 10 0 379 19 385 112 5 521 83 420 0 0 503 9 513 1 0 523 1926 31 49 6 0 86 1 110 31 1 143 14 106 2 0 122 0 154 1 0 155 50635 53 4 0 92 5 128 34 0 167 23 64 5 0 92 2 134 0 0 136 48760 57 2 0 119 0 105 36 3 144 21 77 3 0 101 1 104 1 1 107 47147 64 3 0 114 4 144 28 1 177 21 48 1 0 70 1 112 0 0 113 474 173 223 15 0 411 10 487 129 5 631 79 295 11 0 385 4 504 2 1 511 1938 44 50 2 0 96 4 138 33 0 175 21 61 5 0 87 0 117 1 0 118 47636 48 7 0 91 8 111 33 3 155 19 52 0 0 71 1 118 0 0 119 43638 52 5 0 95 6 120 23 3 152 25 57 5 0 87 0 101 1 1 103 43740 38 5 0 83 5 140 24 2 171 28 53 1 0 82 4 125 0 0 129 465 158 188 19 0 365 23 509 113 8 653 93 223 11 0 327 5 461 2 1 469 1814 32 39 1 0 72 5 107 32 1 145 16 55 4 0 75 1 122 0 0 123 41523 29 3 0 55 5 113 19 0 137 19 49 2 0 70 4 123 4 0 131 39330 35 4 0 69 9 95 22 2 128 26 54 4 0 84 3 103 3 1 110 39134 50 5 0 89 5 112 38 3 158 20 52 3 0 75 1 109 2 1 113 435 119 153 13 0 285 24 427 111 6 568 81 210 13 0 304 9 457 9 2 477 1634 \xa0 36 34 6 1 77 4 113 30 0 147 11 61 2 0 74 0 103 0 0 103 40154 34 4 0 92 1 111 21 1 134 24 46 4 0 74 2 110 0 0 112 41237 32 12 0 81 5 116 22 1 144 15 59 0 0 74 0 75 1 0 76 37529 61 7 0 97 4 97 37 1 139 12 37 2 0 51 5 90 2 0 97 384 156 161 29 1 347 14 437 110 3 564 62 203 8 0 273 7 378 3 0 388 1572 31 40 4 0 75 12 97 29 2 140 17 51 0 0 68 2 88 0 0 90 37322 36 6 0 64 1 104 26 2 133 17 72 1 0 90 0 92 0 0 92 37941 38 4 0 83 6 91 31 2 130 14 63 2 0 79 2 82 0 0 84 37626 51 3 0 80 5 95 25 1 126 18 70 2 0 90 4 96 0 0 100 396 120 165 17 0 302 24 387 111 7 529 66 256 5 0 327 8 358 0 0 366 1524 31 55 12 0 98 3 101 25 1 130 26 78 3 0 107 2 90 0 1 93 42827 68 8 0 103 3 112 28 1 144 16 55 4 0 75 0 108 1 0 109 43134 54 6 0 94 3 127 41 2 173 19 60 2 0 81 1 106 2 0 109 45722 55 6 0 83 4 119 47 0 170 23 52 4 0 79 4 94 0 1 99 431 114 232 32 0 378 13 459 141 4 617 84 245 13 0 342 7 398 3 2 410 1747 27 64 11 0 102 6 128 34 2 170 13 59 0 0 72 1 109 0 0 110 45424 71 8 0 103 5 118 47 0 170 18 59 3 0 80 0 116 2 0 118 47127 68 10 0 105 1 119 55 2 177 19 77 1 0 97 0 90 0 0 90 46926 67 14 0 107 5 119 46 4 174 35 54 2 0 91 0 127 0 0 127 499 104 270 43 0 417 17 484 182 8 691 85 249 6 0 340 1 442 2 0 445 1893 25 79 14 0 118 8 147 43 0 198 20 74 4 0 98 4 98 0 0 102 51623 74 13 0 110 7 130 36 0 173 30 71 3 0 104 3 134 0 0 137 52426 67 11 0 104 6 125 50 1 182 34 52 3 0 89 4 108 0 0 112 48734 72 8 0 114 7 94 54 0 155 36 51 3 0 90 2 149 0 0 151 510 108 292 46 0 446 28 496 183 1 708 120 248 13 0 381 13 489 0 0 502 2037 34 77 17 0 128 4 143 44 2 193 39 67 0 0 106 5 148 0 0 153 58032 79 9 0 120 6 156 51 3 216 26 73 3 0 102 1 111 1 0 113 55139 66 10 0 115 3 140 51 0 194 21 62 0 0 83 3 120 1 0 124 51624 58 16 0 98 7 143 63 1 214 21 53 9 0 83 3 119 0 0 122 517 129 280 52 0 461 20 582 209 6 817 107 255 12 0 374 12 498 2 0 512 2164 39 67 10 0 116 5 159 40 0 204 26 43 4 0 73 7 146 1 0 154 547 46 68 13 0 127 9 135 38 0 182 41 62 6 0 109 6 108 0 1 115 53354 58 12 0 124 11 131 47 0 189 21 39 6 0 66 6 96 0 0 102 48150 57 3 0 110 6 120 53 0 179 27 38 5 0 70 2 125 1 0 128 487 189 250 38 0 477 31 545 178 0 754 115 182 21 0 318 21 475 2 1 499 2048 1680 2627 333 1 4641 235 5636 1704 54 7629 1065 3203 116 0 4384 101 5445 33 7 5586 22240 36.2 56.6 7.2 0.0 3.1 73.9 22.3 0.7 24.3 73.1 2.6 0.0 1.8 97.5 0.6 0.1 7.6 11.8 1.5 0.0 20.9 1.1 25.3 7.7 0.2 34.3 4.8 14.4 0.5 0.0 19.7 0.5 24.5 0.1 0.0 25.1 3472 6897 4432 7439 22240 1662 2591 318 1 4572 223 5183 1643 52 7101 1027 3167 112 0 4306 100 5001 31 6 5138 21117 98.9 98.6 95.5 100.0 98.5 94.9 92.0 96.4 96.3 93.1 96.4 98.9 96.6 0.0 98.2 99.0 91.8 93.9 85.7 92.0 95.0 3422 6398 4334 6963 21117 18 36 15 0 69 12 453 61 2 528 38 36 4 0 78 1 444 2 1 448 1123 1.1 1.4 4.5 0.0 1.5 5.1 8.0 3.6 3.7 6.9 3.6 1.1 3.4 0.0 1.8 1.0 8.2 6.1 14.3 8.0 5.0 50 499 98 476 1123 \xa0from from from from 8:45\xa0AM Total Approach \xa0%Grand\xa0TotalHuntington \xa0Avenue North East South WestParker\xa0Street Forsyth\xa0Way Huntington \xa0Avenue 7:45\xa0AM 8:00\xa0AM 9:00\xa0AM 9:15\xa0AM 9:30\xa0AM 9:45\xa0AM Total 10:00\xa0AM 5:00\xa0PM 5:15\xa0PM 5:30\xa0PMTotal3:30\xa0PM 3:45\xa0PM Total 4:00\xa0PM2:45\xa0PM Total 3:00\xa0PM 3:15\xa0PM2:15\xa0PM 2:30\xa0PM 6:00\xa0PM10:15\xa0AM Heavy\xa0VehiclesExiting\xa0Leg\xa0Total%\xa0CarsCars10:30\xa0AM 4:15\xa0PM 4:30\xa0PM 4:45\xa0PM 5:45\xa0PM TotalTotal 2:00\xa0PM11:30\xa0AM 11:45\xa0AM Total8:15\xa0AM 8:30\xa0AM 10:45\xa0AM Total 1:00\xa0PM 1:15\xa0PM 1:30\xa0PM 1:45\xa0PM12:00\xa0PM 12:15\xa0PM 12:30\xa0PM 12:45\xa0PM TotalTotal 11:15\xa0AM11:00\xa0AM7:00\xa0AM 7:15\xa0AM 7:30\xa0AM Total\xa0\xa0Cars\xa0and\xa0Heavy\xa0Vehicles\xa0(Combined)PDI\xa0File\xa0#: Location: Location: City,\xa0State: Client: Site\xa0Code: Count\xa0Date: Start\xa0Time: End\xa0Time: Class:175870\xa0(10) N:\xa0Forsyth\xa0Way\xa0S:\xa0Parker\xa0Street\xa0\xa0 E:\xa0Huntington \xa0Avenue\xa0W:\xa0Huntington \xa0Avenue\xa0\xa0 Boston,\xa0MA TetraTech/ \xa0S.\xa0Patangay 143‐3946‐17001.02 Wednesday, \xa0October\xa018,\xa02017 Total\xa0% Exiting\xa0Leg\xa0Total%\xa0Heavy\xa0Vehicles6:15\xa0PM7:00\xa0AM 7:00\xa0PM 6:30\xa0PM 6:45\xa0PM Exiting\xa0Leg\xa0TotalTotal Page\xa01 PRECISION D A T A INDUSTRIES, LLC 46 Morton Street, Framingham, MA 01702  Office: 508-875-0100   Fax: 508-875-0118  Email: datarequests@pdillc.com'

In [61]:
ind_2048 = demand_text.index('2048')
demand_text = demand_text[:ind_2048 + 4]
demand_text

'\xa0 Right Thru Left U-Turn Total Right Thru Left U-Turn Total Right Thru Left U-Turn Total Right Thru Left U-Turn Total 47 63 4 0 114 0 121 16 0 137 20 112 0 0 132 1 94 0 0 95 478 49 45 5 0 99 8 108 27 0 143 16 109 1 0 126 1 102 1 0 104 47218 55 9 0 82 1 105 34 0 140 24 99 1 0 124 1 134 4 0 139 48525 52 1 0 78 3 104 48 1 156 30 97 1 0 128 2 142 2 0 146 508 139 215 19 0 373 12 438 125 1 576 90 417 3 0 510 5 472 7 0 484 1943 53 61 4 0 118 5 83 23 0 111 27 114 0 0 141 3 132 1 0 136 50643 49 4 0 96 5 90 24 0 119 20 116 0 0 136 1 112 0 0 113 46436 50 2 0 88 5 90 36 0 131 10 107 0 0 117 1 135 0 0 136 47239 38 0 0 77 4 122 29 5 160 26 83 0 0 109 4 134 0 0 138 484 171 198 10 0 379 19 385 112 5 521 83 420 0 0 503 9 513 1 0 523 1926 31 49 6 0 86 1 110 31 1 143 14 106 2 0 122 0 154 1 0 155 50635 53 4 0 92 5 128 34 0 167 23 64 5 0 92 2 134 0 0 136 48760 57 2 0 119 0 105 36 3 144 21 77 3 0 101 1 104 1 1 107 47147 64 3 0 114 4 144 28 1 177 21 48 1 0 70 1 112 0 0 113 474 173 223 15 0 411 10 487 129 5 631 79 295 11 0 385 4 504 2 1 511 1938 44 50 2 0 96 4 138 33 0 175 21 61 5 0 87 0 117 1 0 118 47636 48 7 0 91 8 111 33 3 155 19 52 0 0 71 1 118 0 0 119 43638 52 5 0 95 6 120 23 3 152 25 57 5 0 87 0 101 1 1 103 43740 38 5 0 83 5 140 24 2 171 28 53 1 0 82 4 125 0 0 129 465 158 188 19 0 365 23 509 113 8 653 93 223 11 0 327 5 461 2 1 469 1814 32 39 1 0 72 5 107 32 1 145 16 55 4 0 75 1 122 0 0 123 41523 29 3 0 55 5 113 19 0 137 19 49 2 0 70 4 123 4 0 131 39330 35 4 0 69 9 95 22 2 128 26 54 4 0 84 3 103 3 1 110 39134 50 5 0 89 5 112 38 3 158 20 52 3 0 75 1 109 2 1 113 435 119 153 13 0 285 24 427 111 6 568 81 210 13 0 304 9 457 9 2 477 1634 \xa0 36 34 6 1 77 4 113 30 0 147 11 61 2 0 74 0 103 0 0 103 40154 34 4 0 92 1 111 21 1 134 24 46 4 0 74 2 110 0 0 112 41237 32 12 0 81 5 116 22 1 144 15 59 0 0 74 0 75 1 0 76 37529 61 7 0 97 4 97 37 1 139 12 37 2 0 51 5 90 2 0 97 384 156 161 29 1 347 14 437 110 3 564 62 203 8 0 273 7 378 3 0 388 1572 31 40 4 0 75 12 97 29 2 140 17 51 0 0 68 2 88 0 0 90 37322 36 6 0 64 1 104 26 2 133 17 72 1 0 90 0 92 0 0 92 37941 38 4 0 83 6 91 31 2 130 14 63 2 0 79 2 82 0 0 84 37626 51 3 0 80 5 95 25 1 126 18 70 2 0 90 4 96 0 0 100 396 120 165 17 0 302 24 387 111 7 529 66 256 5 0 327 8 358 0 0 366 1524 31 55 12 0 98 3 101 25 1 130 26 78 3 0 107 2 90 0 1 93 42827 68 8 0 103 3 112 28 1 144 16 55 4 0 75 0 108 1 0 109 43134 54 6 0 94 3 127 41 2 173 19 60 2 0 81 1 106 2 0 109 45722 55 6 0 83 4 119 47 0 170 23 52 4 0 79 4 94 0 1 99 431 114 232 32 0 378 13 459 141 4 617 84 245 13 0 342 7 398 3 2 410 1747 27 64 11 0 102 6 128 34 2 170 13 59 0 0 72 1 109 0 0 110 45424 71 8 0 103 5 118 47 0 170 18 59 3 0 80 0 116 2 0 118 47127 68 10 0 105 1 119 55 2 177 19 77 1 0 97 0 90 0 0 90 46926 67 14 0 107 5 119 46 4 174 35 54 2 0 91 0 127 0 0 127 499 104 270 43 0 417 17 484 182 8 691 85 249 6 0 340 1 442 2 0 445 1893 25 79 14 0 118 8 147 43 0 198 20 74 4 0 98 4 98 0 0 102 51623 74 13 0 110 7 130 36 0 173 30 71 3 0 104 3 134 0 0 137 52426 67 11 0 104 6 125 50 1 182 34 52 3 0 89 4 108 0 0 112 48734 72 8 0 114 7 94 54 0 155 36 51 3 0 90 2 149 0 0 151 510 108 292 46 0 446 28 496 183 1 708 120 248 13 0 381 13 489 0 0 502 2037 34 77 17 0 128 4 143 44 2 193 39 67 0 0 106 5 148 0 0 153 58032 79 9 0 120 6 156 51 3 216 26 73 3 0 102 1 111 1 0 113 55139 66 10 0 115 3 140 51 0 194 21 62 0 0 83 3 120 1 0 124 51624 58 16 0 98 7 143 63 1 214 21 53 9 0 83 3 119 0 0 122 517 129 280 52 0 461 20 582 209 6 817 107 255 12 0 374 12 498 2 0 512 2164 39 67 10 0 116 5 159 40 0 204 26 43 4 0 73 7 146 1 0 154 547 46 68 13 0 127 9 135 38 0 182 41 62 6 0 109 6 108 0 1 115 53354 58 12 0 124 11 131 47 0 189 21 39 6 0 66 6 96 0 0 102 48150 57 3 0 110 6 120 53 0 179 27 38 5 0 70 2 125 1 0 128 487 189 250 38 0 477 31 545 178 0 754 115 182 21 0 318 21 475 2 1 499 2048'

In [64]:
lines = demand_text.split()#[20:]
lines_int = []
issue = 0
for line in lines:
    try:
        line = int(line)
        if (line > 2164):
            line_0 = int(line / 100)
            line_1 = line % 100
            lines_int.append(line_0)
            lines_int.append(line_1)
        else:
            lines_int.append(line)
    except:
        continue
lines_int

[47,
 63,
 4,
 0,
 114,
 0,
 121,
 16,
 0,
 137,
 20,
 112,
 0,
 0,
 132,
 1,
 94,
 0,
 0,
 95,
 478,
 49,
 45,
 5,
 0,
 99,
 8,
 108,
 27,
 0,
 143,
 16,
 109,
 1,
 0,
 126,
 1,
 102,
 1,
 0,
 104,
 472,
 18,
 55,
 9,
 0,
 82,
 1,
 105,
 34,
 0,
 140,
 24,
 99,
 1,
 0,
 124,
 1,
 134,
 4,
 0,
 139,
 485,
 25,
 52,
 1,
 0,
 78,
 3,
 104,
 48,
 1,
 156,
 30,
 97,
 1,
 0,
 128,
 2,
 142,
 2,
 0,
 146,
 508,
 139,
 215,
 19,
 0,
 373,
 12,
 438,
 125,
 1,
 576,
 90,
 417,
 3,
 0,
 510,
 5,
 472,
 7,
 0,
 484,
 1943,
 53,
 61,
 4,
 0,
 118,
 5,
 83,
 23,
 0,
 111,
 27,
 114,
 0,
 0,
 141,
 3,
 132,
 1,
 0,
 136,
 506,
 43,
 49,
 4,
 0,
 96,
 5,
 90,
 24,
 0,
 119,
 20,
 116,
 0,
 0,
 136,
 1,
 112,
 0,
 0,
 113,
 464,
 36,
 50,
 2,
 0,
 88,
 5,
 90,
 36,
 0,
 131,
 10,
 107,
 0,
 0,
 117,
 1,
 135,
 0,
 0,
 136,
 472,
 39,
 38,
 0,
 0,
 77,
 4,
 122,
 29,
 5,
 160,
 26,
 83,
 0,
 0,
 109,
 4,
 134,
 0,
 0,
 138,
 484,
 171,
 198,
 10,
 0,
 379,
 19,
 385,
 112,
 5,
 521,
 83,
 420,
 0,
 0,
 503,
 9,
 513,
 1,
 0,
 523,
 1926,
 31,
 49,
 6,
 0,
 86,
 1,
 110,
 31,
 1,
 143,
 14,
 106,
 2,
 0,
 122,
 0,
 154,
 1,
 0,
 155,
 506,
 35,
 53,
 4,
 0,
 92,
 5,
 128,
 34,
 0,
 167,
 23,
 64,
 5,
 0,
 92,
 2,
 134,
 0,
 0,
 136,
 487,
 60,
 57,
 2,
 0,
 119,
 0,
 105,
 36,
 3,
 144,
 21,
 77,
 3,
 0,
 101,
 1,
 104,
 1,
 1,
 107,
 471,
 47,
 64,
 3,
 0,
 114,
 4,
 144,
 28,
 1,
 177,
 21,
 48,
 1,
 0,
 70,
 1,
 112,
 0,
 0,
 113,
 474,
 173,
 223,
 15,
 0,
 411,
 10,
 487,
 129,
 5,
 631,
 79,
 295,
 11,
 0,
 385,
 4,
 504,
 2,
 1,
 511,
 1938,
 44,
 50,
 2,
 0,
 96,
 4,
 138,
 33,
 0,
 175,
 21,
 61,
 5,
 0,
 87,
 0,
 117,
 1,
 0,
 118,
 476,
 36,
 48,
 7,
 0,
 91,
 8,
 111,
 33,
 3,
 155,
 19,
 52,
 0,
 0,
 71,
 1,
 118,
 0,
 0,
 119,
 436,
 38,
 52,
 5,
 0,
 95,
 6,
 120,
 23,
 3,
 152,
 25,
 57,
 5,
 0,
 87,
 0,
 101,
 1,
 1,
 103,
 437,
 40,
 38,
 5,
 0,
 83,
 5,
 140,
 24,
 2,
 171,
 28,
 53,
 1,
 0,
 82,
 4,
 125,
 0,
 0,
 129,
 465,
 158,
 188,
 19,
 0,
 365,
 23,
 509,
 113,
 8,
 653,
 93,
 223,
 11,
 0,
 327,
 5,
 461,
 2,
 1,
 469,
 1814,
 32,
 39,
 1,
 0,
 72,
 5,
 107,
 32,
 1,
 145,
 16,
 55,
 4,
 0,
 75,
 1,
 122,
 0,
 0,
 123,
 415,
 23,
 29,
 3,
 0,
 55,
 5,
 113,
 19,
 0,
 137,
 19,
 49,
 2,
 0,
 70,
 4,
 123,
 4,
 0,
 131,
 393,
 30,
 35,
 4,
 0,
 69,
 9,
 95,
 22,
 2,
 128,
 26,
 54,
 4,
 0,
 84,
 3,
 103,
 3,
 1,
 110,
 391,
 34,
 50,
 5,
 0,
 89,
 5,
 112,
 38,
 3,
 158,
 20,
 52,
 3,
 0,
 75,
 1,
 109,
 2,
 1,
 113,
 435,
 119,
 153,
 13,
 0,
 285,
 24,
 427,
 111,
 6,
 568,
 81,
 210,
 13,
 0,
 304,
 9,
 457,
 9,
 2,
 477,
 1634,
 36,
 34,
 6,
 1,
 77,
 4,
 113,
 30,
 0,
 147,
 11,
 61,
 2,
 0,
 74,
 0,
 103,
 0,
 0,
 103,
 401,
 54,
 34,
 4,
 0,
 92,
 1,
 111,
 21,
 1,
 134,
 24,
 46,
 4,
 0,
 74,
 2,
 110,
 0,
 0,
 112,
 412,
 37,
 32,
 12,
 0,
 81,
 5,
 116,
 22,
 1,
 144,
 15,
 59,
 0,
 0,
 74,
 0,
 75,
 1,
 0,
 76,
 375,
 29,
 61,
 7,
 0,
 97,
 4,
 97,
 37,
 1,
 139,
 12,
 37,
 2,
 0,
 51,
 5,
 90,
 2,
 0,
 97,
 384,
 156,
 161,
 29,
 1,
 347,
 14,
 437,
 110,
 3,
 564,
 62,
 203,
 8,
 0,
 273,
 7,
 378,
 3,
 0,
 388,
 1572,
 31,
 40,
 4,
 0,
 75,
 12,
 97,
 29,
 2,
 140,
 17,
 51,
 0,
 0,
 68,
 2,
 88,
 0,
 0,
 90,
 373,
 22,
 36,
 6,
 0,
 64,
 1,
 104,
 26,
 2,
 133,
 17,
 72,
 1,
 0,
 90,
 0,
 92,
 0,
 0,
 92,
 379,
 41,
 38,
 4,
 0,
 83,
 6,
 91,
 31,
 2,
 130,
 14,
 63,
 2,
 0,
 79,
 2,
 82,
 0,
 0,
 84,
 376,
 26,
 51,
 3,
 0,
 80,
 5,
 95,
 25,
 1,
 126,
 18,
 70,
 2,
 0,
 90,
 4,
 96,
 0,
 0,
 100,
 396,
 120,
 165,
 17,
 0,
 302,
 24,
 387,
 111,
 7,
 529,
 66,
 256,
 5,
 0,
 327,
 8,
 358,
 0,
 0,
 366,
 1524,
 31,
 55,
 12,
 0,
 98,
 3,
 101,
 25,
 1,
 130,
 26,
 78,
 3,
 0,
 107,
 2,
 90,
 0,
 1,
 93,
 428,
 27,
 68,
 8,
 0,
 103,
 3,
 112,
 28,
 1,
 144,
 16,
 55,
 4,
 0,
 75,
 0,
 108,
 1,
 0,
 109,
 431,
 34,
 54,
 6,
 0,
 94,
 3,
 127,
 41,
 2,
 173,
 19,
 60,
 2,
 0,
 81,
 1,
 106,
 2,
 0,
 109,
 457,
 22,
 55,
 6,
 0,
 83,
 4,
 119,
 47,
 0,
 170,
 23,
 52,
 4,
 0,
 79,
 4,
 94,
 0,
 1,
 99,
 431,
 114,
 232,
 32,
 0,
 378,
 13,
 459,
 141,
 4,
 617,
 84,
 245,
 13,
 0,
 342,
 7,
 398,
 3,
 2,
 410,
 1747,
 27,
 64,
 11,
 0,
 102,
 6,
 128,
 34,
 2,
 170,
 13,
 59,
 0,
 0,
 72,
 1,
 109,
 0,
 0,
 110,
 454,
 24,
 71,
 8,
 0,
 103,
 5,
 118,
 47,
 0,
 170,
 18,
 59,
 3,
 0,
 80,
 0,
 116,
 2,
 0,
 118,
 471,
 27,
 68,
 10,
 0,
 105,
 1,
 119,
 55,
 2,
 177,
 19,
 77,
 1,
 0,
 97,
 0,
 90,
 0,
 0,
 90,
 469,
 26,
 67,
 14,
 0,
 107,
 5,
 119,
 46,
 4,
 174,
 35,
 54,
 2,
 0,
 91,
 0,
 127,
 0,
 0,
 127,
 499,
 104,
 270,
 43,
 0,
 417,
 17,
 484,
 182,
 8,
 691,
 85,
 249,
 6,
 0,
 340,
 1,
 442,
 2,
 0,
 445,
 1893,
 25,
 79,
 14,
 0,
 118,
 8,
 147,
 43,
 0,
 198,
 20,
 74,
 4,
 0,
 98,
 4,
 98,
 0,
 0,
 102,
 516,
 23,
 74,
 13,
 0,
 110,
 7,
 130,
 36,
 0,
 173,
 30,
 71,
 3,
 0,
 104,
 3,
 134,
 0,
 0,
 137,
 524,
 26,
 67,
 11,
 0,
 104,
 6,
 125,
 50,
 1,
 182,
 34,
 52,
 3,
 ...]

In [65]:
len(lines_int)

1260

In [76]:
line_len = 21
line_index = 0
lines_clean = []
cur_line = []
for line in lines_int:
    if (line_index % line_len == 0 and len(cur_line) > 0):
        lines_clean.append(cur_line)
        cur_line = []
    cur_line.append(line)
    line_index += 1
lines_clean.append(cur_line)
lines_clean

[[47,
  63,
  4,
  0,
  114,
  0,
  121,
  16,
  0,
  137,
  20,
  112,
  0,
  0,
  132,
  1,
  94,
  0,
  0,
  95,
  478],
 [49,
  45,
  5,
  0,
  99,
  8,
  108,
  27,
  0,
  143,
  16,
  109,
  1,
  0,
  126,
  1,
  102,
  1,
  0,
  104,
  472],
 [18,
  55,
  9,
  0,
  82,
  1,
  105,
  34,
  0,
  140,
  24,
  99,
  1,
  0,
  124,
  1,
  134,
  4,
  0,
  139,
  485],
 [25,
  52,
  1,
  0,
  78,
  3,
  104,
  48,
  1,
  156,
  30,
  97,
  1,
  0,
  128,
  2,
  142,
  2,
  0,
  146,
  508],
 [139,
  215,
  19,
  0,
  373,
  12,
  438,
  125,
  1,
  576,
  90,
  417,
  3,
  0,
  510,
  5,
  472,
  7,
  0,
  484,
  1943],
 [53,
  61,
  4,
  0,
  118,
  5,
  83,
  23,
  0,
  111,
  27,
  114,
  0,
  0,
  141,
  3,
  132,
  1,
  0,
  136,
  506],
 [43,
  49,
  4,
  0,
  96,
  5,
  90,
  24,
  0,
  119,
  20,
  116,
  0,
  0,
  136,
  1,
  112,
  0,
  0,
  113,
  464],
 [36,
  50,
  2,
  0,
  88,
  5,
  90,
  36,
  0,
  131,
  10,
  107,
  0,
  0,
  117,
  1,
  135,
  0,
  0,
  136,
  472],
 [39,
  38,
  0,
  0,
  77,
  4,
  122,
  29,
  5,
  160,
  26,
  83,
  0,
  0,
  109,
  4,
  134,
  0,
  0,
  138,
  484],
 [171,
  198,
  10,
  0,
  379,
  19,
  385,
  112,
  5,
  521,
  83,
  420,
  0,
  0,
  503,
  9,
  513,
  1,
  0,
  523,
  1926],
 [31,
  49,
  6,
  0,
  86,
  1,
  110,
  31,
  1,
  143,
  14,
  106,
  2,
  0,
  122,
  0,
  154,
  1,
  0,
  155,
  506],
 [35,
  53,
  4,
  0,
  92,
  5,
  128,
  34,
  0,
  167,
  23,
  64,
  5,
  0,
  92,
  2,
  134,
  0,
  0,
  136,
  487],
 [60,
  57,
  2,
  0,
  119,
  0,
  105,
  36,
  3,
  144,
  21,
  77,
  3,
  0,
  101,
  1,
  104,
  1,
  1,
  107,
  471],
 [47,
  64,
  3,
  0,
  114,
  4,
  144,
  28,
  1,
  177,
  21,
  48,
  1,
  0,
  70,
  1,
  112,
  0,
  0,
  113,
  474],
 [173,
  223,
  15,
  0,
  411,
  10,
  487,
  129,
  5,
  631,
  79,
  295,
  11,
  0,
  385,
  4,
  504,
  2,
  1,
  511,
  1938],
 [44,
  50,
  2,
  0,
  96,
  4,
  138,
  33,
  0,
  175,
  21,
  61,
  5,
  0,
  87,
  0,
  117,
  1,
  0,
  118,
  476],
 [36,
  48,
  7,
  0,
  91,
  8,
  111,
  33,
  3,
  155,
  19,
  52,
  0,
  0,
  71,
  1,
  118,
  0,
  0,
  119,
  436],
 [38,
  52,
  5,
  0,
  95,
  6,
  120,
  23,
  3,
  152,
  25,
  57,
  5,
  0,
  87,
  0,
  101,
  1,
  1,
  103,
  437],
 [40,
  38,
  5,
  0,
  83,
  5,
  140,
  24,
  2,
  171,
  28,
  53,
  1,
  0,
  82,
  4,
  125,
  0,
  0,
  129,
  465],
 [158,
  188,
  19,
  0,
  365,
  23,
  509,
  113,
  8,
  653,
  93,
  223,
  11,
  0,
  327,
  5,
  461,
  2,
  1,
  469,
  1814],
 [32,
  39,
  1,
  0,
  72,
  5,
  107,
  32,
  1,
  145,
  16,
  55,
  4,
  0,
  75,
  1,
  122,
  0,
  0,
  123,
  415],
 [23,
  29,
  3,
  0,
  55,
  5,
  113,
  19,
  0,
  137,
  19,
  49,
  2,
  0,
  70,
  4,
  123,
  4,
  0,
  131,
  393],
 [30,
  35,
  4,
  0,
  69,
  9,
  95,
  22,
  2,
  128,
  26,
  54,
  4,
  0,
  84,
  3,
  103,
  3,
  1,
  110,
  391],
 [34,
  50,
  5,
  0,
  89,
  5,
  112,
  38,
  3,
  158,
  20,
  52,
  3,
  0,
  75,
  1,
  109,
  2,
  1,
  113,
  435],
 [119,
  153,
  13,
  0,
  285,
  24,
  427,
  111,
  6,
  568,
  81,
  210,
  13,
  0,
  304,
  9,
  457,
  9,
  2,
  477,
  1634],
 [36,
  34,
  6,
  1,
  77,
  4,
  113,
  30,
  0,
  147,
  11,
  61,
  2,
  0,
  74,
  0,
  103,
  0,
  0,
  103,
  401],
 [54,
  34,
  4,
  0,
  92,
  1,
  111,
  21,
  1,
  134,
  24,
  46,
  4,
  0,
  74,
  2,
  110,
  0,
  0,
  112,
  412],
 [37,
  32,
  12,
  0,
  81,
  5,
  116,
  22,
  1,
  144,
  15,
  59,
  0,
  0,
  74,
  0,
  75,
  1,
  0,
  76,
  375],
 [29, 61, 7, 0, 97, 4, 97, 37, 1, 139, 12, 37, 2, 0, 51, 5, 90, 2, 0, 97, 384],
 [156,
  161,
  29,
  1,
  347,
  14,
  437,
  110,
  3,
  564,
  62,
  203,
  8,
  0,
  273,
  7,
  378,
  3,
  0,
  388,
  1572],
 [31,
  40,
  4,
  0,
  75,
  12,
  97,
  29,
  2,
  140,
  17,
  51,
  0,
  0,
  68,
  2,
  88,
  0,
  0,
  90,
  373],
 [22,
  36,
  6,
  0,
  64,
  1,
  104,
  26,
  2,
  133,
  17,
  72,
  1,
  0,
  90,
  0,
  92,
  0,
  0,
  92,
  379],
 [41, 38, 4, 0, 83, 6, 91, 31, 2, 130, 14, 63, 2, 0, 79, 2, 82, 0, 0, 84, 376],
 [26,
  51,
  3,
  0,
  80,
  5,
  95,
  25,
  1,
  126,
  18,
  70,
  2,
  0,
  90,
  4,
  96,
  0,
  0,
  100,
  396],
 [120,
  165,
  17,
  0,
  302,
  24,
  387,
  111,
  7,
  529,
  66,
  256,
  5,
  0,
  327,
  8,
  358,
  0,
  0,
  366,
  1524],
 [31,
  55,
  12,
  0,
  98,
  3,
  101,
  25,
  1,
  130,
  26,
  78,
  3,
  0,
  107,
  2,
  90,
  0,
  1,
  93,
  428],
 [27,
  68,
  8,
  0,
  103,
  3,
  112,
  28,
  1,
  144,
  16,
  55,
  4,
  0,
  75,
  0,
  108,
  1,
  0,
  109,
  431],
 [34,
  54,
  6,
  0,
  94,
  3,
  127,
  41,
  2,
  173,
  19,
  60,
  2,
  0,
  81,
  1,
  106,
  2,
  0,
  109,
  457],
 [22,
  55,
  6,
  0,
  83,
  4,
  119,
  47,
  0,
  170,
  23,
  52,
  4,
  0,
  79,
  4,
  94,
  0,
  1,
  99,
  431],
 [114,
  232,
  32,
  0,
  378,
  13,
  459,
  141,
  4,
  617,
  84,
  245,
  13,
  0,
  342,
  7,
  398,
  3,
  2,
  410,
  1747],
 [27,
  64,
  11,
  0,
  102,
  6,
  128,
  34,
  2,
  170,
  13,
  59,
  0,
  0,
  72,
  1,
  109,
  0,
  0,
  110,
  454],
 [24,
  71,
  8,
  0,
  103,
  5,
  118,
  47,
  0,
  170,
  18,
  59,
  3,
  0,
  80,
  0,
  116,
  2,
  0,
  118,
  471],
 [27,
  68,
  10,
  0,
  105,
  1,
  119,
  55,
  2,
  177,
  19,
  77,
  1,
  0,
  97,
  0,
  90,
  0,
  0,
  90,
  469],
 [26,
  67,
  14,
  0,
  107,
  5,
  119,
  46,
  4,
  174,
  35,
  54,
  2,
  0,
  91,
  0,
  127,
  0,
  0,
  127,
  499],
 [104,
  270,
  43,
  0,
  417,
  17,
  484,
  182,
  8,
  691,
  85,
  249,
  6,
  0,
  340,
  1,
  442,
  2,
  0,
  445,
  1893],
 [25,
  79,
  14,
  0,
  118,
  8,
  147,
  43,
  0,
  198,
  20,
  74,
  4,
  0,
  98,
  4,
  98,
  0,
  0,
  102,
  516],
 [23,
  74,
  13,
  0,
  110,
  7,
  130,
  36,
  0,
  173,
  30,
  71,
  3,
  0,
  104,
  3,
  134,
  0,
  0,
  137,
  524],
 [26,
  67,
  11,
  0,
  104,
  6,
  125,
  50,
  1,
  182,
  34,
  52,
  3,
  0,
  89,
  4,
  108,
  0,
  0,
  112,
  487],
 [34,
  72,
  8,
  0,
  114,
  7,
  94,
  54,
  0,
  155,
  36,
  51,
  3,
  0,
  90,
  2,
  149,
  0,
  0,
  151,
  510],
 [108,
  292,
  46,
  0,
  446,
  28,
  496,
  183,
  1,
  708,
  120,
  248,
  13,
  0,
  381,
  13,
  489,
  0,
  0,
  502,
  2037],
 [34,
  77,
  17,
  0,
  128,
  4,
  143,
  44,
  2,
  193,
  39,
  67,
  0,
  0,
  106,
  5,
  148,
  0,
  0,
  153,
  580],
 [32,
  79,
  9,
  0,
  120,
  6,
  156,
  51,
  3,
  216,
  26,
  73,
  3,
  0,
  102,
  1,
  111,
  1,
  0,
  113,
  551],
 [39,
  66,
  10,
  0,
  115,
  3,
  140,
  51,
  0,
  194,
  21,
  62,
  0,
  0,
  83,
  3,
  120,
  1,
  0,
  124,
  516],
 [24,
  58,
  16,
  0,
  98,
  7,
  143,
  63,
  1,
  214,
  21,
  53,
  9,
  0,
  83,
  3,
  119,
  0,
  0,
  122,
  517],
 [129,
  280,
  52,
  0,
  461,
  20,
  582,
  209,
  6,
  817,
  107,
  255,
  12,
  0,
  374,
  12,
  498,
  2,
  0,
  512,
  2164],
 [39,
  67,
  10,
  0,
  116,
  5,
  159,
  40,
  0,
  204,
  26,
  43,
  4,
  0,
  73,
  7,
  146,
  1,
  0,
  154,
  547],
 [46,
  68,
  13,
  0,
  127,
  9,
  135,
  38,
  0,
  182,
  41,
  62,
  6,
  0,
  109,
  6,
  108,
  0,
  1,
  115,
  533],
 [54,
  58,
  12,
  0,
  124,
  11,
  131,
  47,
  0,
  189,
  21,
  39,
  6,
  0,
  66,
  6,
  96,
  0,
  0,
  102,
  481],
 [50,
  57,
  3,
  0,
  110,
  6,
  120,
  53,
  0,
  179,
  27,
  38,
  5,
  0,
  70,
  2,
  125,
  1,
  0,
  128,
  487],
 [189,
  250,
  38,
  0,
  477,
  31,
  545,
  178,
  0,
  754,
  115,
  182,
  21,
  0,
  318,
  21,
  475,
  2,
  1,
  499,
  2048]]

In [79]:
dict_data = {'Forsyth Right': [], 'Forsyth Thru': [], 'Forsyth Left': [], 'Forsyth UTurn': [], 'Forsyth Total': [],
       'Huntington from E Right': [], 'Huntington from E Thru': [], 'Huntington from E Left': [],
        'Huntington from E UTurn': [], 'Huntington from E Total': [],
        'Parker Right': [], 'Parker Thru': [], 'Parker Left': [], 'Parker UTurn': [], 'Parker Total': [],
        'Huntington from W Right': [], 'Huntington from W Thru': [], 'Huntington from W Left': [],
        'Huntington from W UTurn': [], 'Huntington from W Total': [], 'Total': []}
dict_data

{'Forsyth Right': [],
 'Forsyth Thru': [],
 'Forsyth Left': [],
 'Forsyth UTurn': [],
 'Forsyth Total': [],
 'Huntington from E Right': [],
 'Huntington from E Thru': [],
 'Huntington from E Left': [],
 'Huntington from E UTurn': [],
 'Huntington from E Total': [],
 'Parker Right': [],
 'Parker Thru': [],
 'Parker Left': [],
 'Parker UTurn': [],
 'Parker Total': [],
 'Huntington from W Right': [],
 'Huntington from W Thru': [],
 'Huntington from W Left': [],
 'Huntington from W UTurn': [],
 'Huntington from W Total': [],
 'Total': []}

In [107]:
for row in lines_clean:
    dict_data['Forsyth Right'].append(row[0])
    dict_data['Forsyth Thru'].append(row[1])
    dict_data['Forsyth Left'].append(row[2])
    dict_data['Forsyth UTurn'].append(row[3])
    dict_data['Forsyth Total'].append(row[4])
    dict_data['Huntington from E Right'].append(row[5])
    dict_data['Huntington from E Thru'].append(row[6])
    dict_data['Huntington from E Left'].append(row[7])
    dict_data['Huntington from E UTurn'].append(row[8])
    dict_data['Huntington from E Total'].append(row[9])
    dict_data['Parker Right'].append(row[10])
    dict_data['Parker Thru'].append(row[11])
    dict_data['Parker Left'].append(row[12])
    dict_data['Parker UTurn'].append(row[13])
    dict_data['Parker Total'].append(row[14])
    dict_data['Huntington from W Right'].append(row[15])
    dict_data['Huntington from W Thru'].append(row[16])
    dict_data['Huntington from W Left'].append(row[17])
    dict_data['Huntington from W UTurn'].append(row[18])
    dict_data['Huntington from W Total'].append(row[19])
    dict_data['Total'].append(row[20])
df_data = pd.DataFrame(dict_data, columns = dict_data.keys())
df_data

,Forsyth Right,Forsyth Thru,Forsyth Left,Forsyth UTurn,Forsyth Total,Huntington from E Right,Huntington from E Thru,Huntington from E Left,Huntington from E UTurn,Huntington from E Total,...,Parker Thru,Parker Left,Parker UTurn,Parker Total,Huntington from W Right,Huntington from W Thru,Huntington from W Left,Huntington from W UTurn,Huntington from W Total,Total
0,47,63,4,0,114,0,121,16,0,137,...,112,0,0,132,1,94,0,0,95,478
1,49,45,5,0,99,8,108,27,0,143,...,109,1,0,126,1,102,1,0,104,472
2,18,55,9,0,82,1,105,34,0,140,...,99,1,0,124,1,134,4,0,139,485
3,25,52,1,0,78,3,104,48,1,156,...,97,1,0,128,2,142,2,0,146,508
4,139,215,19,0,373,12,438,125,1,576,...,417,3,0,510,5,472,7,0,484,1943
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,39,67,10,0,116,5,159,40,0,204,...,43,4,0,73,7,146,1,0,154,547
296,46,68,13,0,127,9,135,38,0,182,...,62,6,0,109,6,108,0,1,115,533
297,54,58,12,0,124,11,131,47,0,189,...,39,6,0,66,6,96,0,0,102,481
298,50,57,3,0,110,6,120,53,0,179,...,38,5,0,70,2,125,1,0,128,487
299,189,250,38,0,477,31,545,178,0,754,...,182,21,0,318,21,475,2,1,499,2048

In [108]:
hr = 7
mins = 0
am = 'am'
secs = 0
total = False
for row in range(len(df_data)):
    if (total):
        df_data.at[row, 'Time'] = str(hr-1) + str(am) + ' total'
        df_data.at[row, 'TimePoint (s from sim start)'] = None
        total = False
    else:
        df_data.at[row, 'Time'] = str(hr) + ':' + str(mins) + str(am)
        df_data.at[row, 'TimePoint (s from sim start)'] = secs
        secs += 900
        mins += 15
        if (mins == 60):
            total = True
            hr += 1
            mins = 0
        if (hr == 13):
            hr = 1
            am = 'pm'
df_data

,Forsyth Right,Forsyth Thru,Forsyth Left,Forsyth UTurn,Forsyth Total,Huntington from E Right,Huntington from E Thru,Huntington from E Left,Huntington from E UTurn,Huntington from E Total,...,Parker UTurn,Parker Total,Huntington from W Right,Huntington from W Thru,Huntington from W Left,Huntington from W UTurn,Huntington from W Total,Total,Time,TimePoint (s from sim start)
0,47,63,4,0,114,0,121,16,0,137,...,0,132,1,94,0,0,95,478,7:0am,0.0
1,49,45,5,0,99,8,108,27,0,143,...,0,126,1,102,1,0,104,472,7:15am,900.0
2,18,55,9,0,82,1,105,34,0,140,...,0,124,1,134,4,0,139,485,7:30am,1800.0
3,25,52,1,0,78,3,104,48,1,156,...,0,128,2,142,2,0,146,508,7:45am,2700.0
4,139,215,19,0,373,12,438,125,1,576,...,0,510,5,472,7,0,484,1943,7am total,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,39,67,10,0,116,5,159,40,0,204,...,0,73,7,146,1,0,154,547,6:0pm,212400.0
296,46,68,13,0,127,9,135,38,0,182,...,0,109,6,108,0,1,115,533,6:15pm,213300.0
297,54,58,12,0,124,11,131,47,0,189,...,0,66,6,96,0,0,102,481,6:30pm,214200.0
298,50,57,3,0,110,6,120,53,0,179,...,0,70,2,125,1,0,128,487,6:45pm,215100.0
299,189,250,38,0,477,31,545,178,0,754,...,0,318,21,475,2,1,499,2048,6pm total,NaN

In [110]:
df_filtered = df_data[~df_data['Time'].map(lambda x: 'total' in x)]
df_filtered

,Forsyth Right,Forsyth Thru,Forsyth Left,Forsyth UTurn,Forsyth Total,Huntington from E Right,Huntington from E Thru,Huntington from E Left,Huntington from E UTurn,Huntington from E Total,...,Parker UTurn,Parker Total,Huntington from W Right,Huntington from W Thru,Huntington from W Left,Huntington from W UTurn,Huntington from W Total,Total,Time,TimePoint (s from sim start)
0,47,63,4,0,114,0,121,16,0,137,...,0,132,1,94,0,0,95,478,7:0am,0.0
1,49,45,5,0,99,8,108,27,0,143,...,0,126,1,102,1,0,104,472,7:15am,900.0
2,18,55,9,0,82,1,105,34,0,140,...,0,124,1,134,4,0,139,485,7:30am,1800.0
3,25,52,1,0,78,3,104,48,1,156,...,0,128,2,142,2,0,146,508,7:45am,2700.0
5,53,61,4,0,118,5,83,23,0,111,...,0,141,3,132,1,0,136,506,8:0am,3600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,24,58,16,0,98,7,143,63,1,214,...,0,83,3,119,0,0,122,517,5:45pm,211500.0
295,39,67,10,0,116,5,159,40,0,204,...,0,73,7,146,1,0,154,547,6:0pm,212400.0
296,46,68,13,0,127,9,135,38,0,182,...,0,109,6,108,0,1,115,533,6:15pm,213300.0
297,54,58,12,0,124,11,131,47,0,189,...,0,66,6,96,0,0,102,481,6:30pm,214200.0
298,50,57,3,0,110,6,120,53,0,179,...,0,70,2,125,1,0,128,487,6:45pm,215100.0

In [111]:
df_final = df_filtered.set_index(['Time', 'TimePoint (s from sim start)'])
df_final

,,Forsyth Right,Forsyth Thru,Forsyth Left,Forsyth UTurn,Forsyth Total,Huntington from E Right,Huntington from E Thru,Huntington from E Left,Huntington from E UTurn,Huntington from E Total,...,Parker Thru,Parker Left,Parker UTurn,Parker Total,Huntington from W Right,Huntington from W Thru,Huntington from W Left,Huntington from W UTurn,Huntington from W Total,Total
Time,TimePoint (s from sim start),,,,,,,,,,,,,,,,,,,,,
7:0am,0.0,47,63,4,0,114,0,121,16,0,137,...,112,0,0,132,1,94,0,0,95,478
7:15am,900.0,49,45,5,0,99,8,108,27,0,143,...,109,1,0,126,1,102,1,0,104,472
7:30am,1800.0,18,55,9,0,82,1,105,34,0,140,...,99,1,0,124,1,134,4,0,139,485
7:45am,2700.0,25,52,1,0,78,3,104,48,1,156,...,97,1,0,128,2,142,2,0,146,508
8:0am,3600.0,53,61,4,0,118,5,83,23,0,111,...,114,0,0,141,3,132,1,0,136,506
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5:45pm,211500.0,24,58,16,0,98,7,143,63,1,214,...,53,9,0,83,3,119,0,0,122,517
6:0pm,212400.0,39,67,10,0,116,5,159,40,0,204,...,43,4,0,73,7,146,1,0,154,547
6:15pm,213300.0,46,68,13,0,127,9,135,38,0,182,...,62,6,0,109,6,108,0,1,115,533
6:30pm,214200.0,54,58,12,0,124,11,131,47,0,189,...,39,6,0,66,6,96,0,0,102,481
6:45pm,215100.0,50,57,3,0,110,6,120,53,0,179,...,38,5,0,70,2,125,1,0,128,487

In [112]:
df_final.head(15)

,,Forsyth Right,Forsyth Thru,Forsyth Left,Forsyth UTurn,Forsyth Total,Huntington from E Right,Huntington from E Thru,Huntington from E Left,Huntington from E UTurn,Huntington from E Total,...,Parker Thru,Parker Left,Parker UTurn,Parker Total,Huntington from W Right,Huntington from W Thru,Huntington from W Left,Huntington from W UTurn,Huntington from W Total,Total
Time,TimePoint (s from sim start),,,,,,,,,,,,,,,,,,,,,
7:0am,0.0,47,63,4,0,114,0,121,16,0,137,...,112,0,0,132,1,94,0,0,95,478
7:15am,900.0,49,45,5,0,99,8,108,27,0,143,...,109,1,0,126,1,102,1,0,104,472
7:30am,1800.0,18,55,9,0,82,1,105,34,0,140,...,99,1,0,124,1,134,4,0,139,485
7:45am,2700.0,25,52,1,0,78,3,104,48,1,156,...,97,1,0,128,2,142,2,0,146,508
8:0am,3600.0,53,61,4,0,118,5,83,23,0,111,...,114,0,0,141,3,132,1,0,136,506
8:15am,4500.0,43,49,4,0,96,5,90,24,0,119,...,116,0,0,136,1,112,0,0,113,464
8:30am,5400.0,36,50,2,0,88,5,90,36,0,131,...,107,0,0,117,1,135,0,0,136,472
8:45am,6300.0,39,38,0,0,77,4,122,29,5,160,...,83,0,0,109,4,134,0,0,138,484
9:0am,7200.0,31,49,6,0,86,1,110,31,1,143,...,106,2,0,122,0,154,1,0,155,506
9:15am,8100.0,35,53,4,0,92,5,128,34,0,167,...,64,5,0,92,2,134,0,0,136,487
9:30am,9000.0,60,57,2,0,119,0,105,36,3,144,...,77,3,0,101,1,104,1,1,107,471
9:45am,9900.0,47,64,3,0,114,4,144,28,1,177,...,48,1,0,70,1,112,0,0,113,474
10:0am,10800.0,44,50,2,0,96,4,138,33,0,175,...,61,5,0,87,0,117,1,0,118,476
10:15am,11700.0,36,48,7,0,91,8,111,33,3,155,...,52,0,0,71,1,118,0,0,119,436
10:30am,12600.0,38,52,5,0,95,6,120,23,3,152,...,57,5,0,87,0,101,1,1,103,437

In [113]:
df_final.to_csv('Intersection Data to Table.csv')